name: DotNet

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v2

      # workaround for dotnet tools not being on path https://github.com/actions/virtual-environments/issues/213
      - run: echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"

      - run: dotnet tool install -g dotnet-format

      - run: dotnet format
